### ISSUE TITLE
Is there a way to encrypt data in my nodejs server and decrypt in my php page?

### ISSUE THREAD

**Issue by wilsntn** [kensnyder/poly-crypto#19]
Hi, im having some problems here is my code.

in node side

`const secret = "seg078691";
const salt = "28yf3rh37rvh2e8vj28eh73rhv28jev28h375h";

var downloadCrypt = PolyAES.withPassword(secret, salt).encrypt(id_post.link);
`
then i pass the 'downloadCrypt' var in url like this

**campanha.php?id=eQ3VQLrk6x3KKe97nziYv2oCg4QSSAEzsb7BQ4uDDToJEyFExOgQyHCOGV4uhQg4oK+3y6OoFc1RrYjQqgjcEk1OwWZ/hYCcE8je9omsBAdYQGlz1q0uE1bkuTM=**

then get by id and

in php side to decrypt..

`<?php 
require_once('../vendor/autoload.php');
use PolyCrypto\PolyAES;

$data = $_GET['id'];

$password = 'seg078691';
$salt = '28yf3rh37rvh2e8vj28eh73rhv28jev28h375h';
echo $decrypted = PolyAES::withPassword($password, $salt)->decrypt($data);
 ?>`

but its not working im doing domething wrong?

**Comment by kensnyder** [comment]
Hi @wilsntn, Base64 is not safe to put in a URL. In your `campanha.php?id=...` you'll notice that there is a plus there. PHP will interpret the plus as a space when populating `$_GET`. You'll need to use encodeURIComponent to make the string safe for a URL.

```js
const encodedId = encodeURIComponent(downloadCrypt);
const link = `campanha.php?id=${encodedId}`;
```

Really, it's best to run encodeURIComponent on every URL param.

Using encodeURIComponent can be confusing and unwieldy, so I actually created a library called [fluent-url](https://www.npmjs.com/package/fluent-url) for working with URLs. Usage:

```js
const url = require('fluent-url');

const link = url('campanha.php', { id: encodedId }).href();
```
