### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by Shadowsith** [kensnyder/poly-crypto#9]
I've seen that your Python code is written in Python 2.7.
Python 2.7 is still in use but it should be legacy.

If you have time you should have a look at that.
If not I'll try it by my own, when I can spent some time for it and make a push request.

**Comment by kensnyder** [comment]
In v2.0.0 of this library I dropped support for Python. We ended up not using Python for our projects so I removed it. I'm not good with Python and I never was able to get this package properly registered on pypi.org.

If you are interested in adding support, you can dig up the v1.x code, make it compatible with Python 3 and add a pull request. But I don't plan to maintain it.
